name: notebeans
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  sqflite: ^2.2.8
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  auto_size_text: ^3.0.0
  flutter_quill: ^7.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Bold.ttf
        - asset: fonts/RobotoMono-BoldItalic.ttf
        - asset: fonts/RobotoMono-Italic.ttf
        - asset: fonts/RobotoMono-Regular.ttf
